#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

echo "CRS production deploy — GitHub + Render checklist"
echo ""
echo "=== GitHub Actions workflow (Deploy Prod) ==="
echo ""
echo "Jobs when DEPLOY_TARGET=render (default):"
echo "  resolve_target → ci → deploy_render"
echo ""
echo "Jobs when DEPLOY_TARGET=k8s:"
echo "  resolve_target → ci → deploy_k8s"
echo ""
echo "=== GitHub (repo Settings → Secrets and variables → Actions) ==="
echo ""
echo "Variable (recommended):"
echo "  DEPLOY_TARGET          render"
echo ""
echo "Required secret for Render:"
echo "  RENDER_DEPLOY_HOOK     https://api.render.com/deploy/srv-...?key=..."
echo "  KUBE_CONFIG_PROD       base64-encoded kubeconfig"
echo "  K8S_OVERLAY_PROD       kustomize overlay path"
echo "  K8S_NAMESPACE_PROD     namespace (e.g. crs-prod)"
echo ""
echo "=== Render Dashboard ==="
echo ""
echo "Service env vars (Environment tab — NOT in GitHub):"
echo "  MONGO_URI              mongodb+srv://..."
echo "  JWT_PRIVATE_KEY        PEM one-liner (./docker/generate-jwt-keys.sh)"
echo "  JWT_PUBLIC_KEY         PEM one-liner"
echo ""
echo "Already in render.yaml (synced on blueprint apply):"
echo "  NODE_ENV, API_PREFIX, UPLOAD_DIR, CORS_ORIGINS, COOKIE_SECURE, etc."
echo ""
echo "One-time Render setup:"
echo "  1. New Blueprint → connect repo → apply render.yaml"
echo "  2. Settings → Deploy Hook → copy URL → GitHub secret RENDER_DEPLOY_HOOK"
echo "  3. autoDeploy is false — only GitHub Actions triggers deploy"
echo "  4. DNS: CNAME crs.abnjain.me → <service>.onrender.com"
echo "  5. After deploy: ./docker/smoke-test.sh https://crs.abnjain.me"
echo "  6. Admin user: Render Shell → node /app/server/dist/scripts/createUser.js ..."
echo ""

if command -v render >/dev/null 2>&1; then
  echo "Render CLI: render blueprint apply"
else
  echo "Render CLI: https://render.com/docs/cli"
fi
