#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

echo "CRS production deploy — GitHub + Render checklist"
echo ""
echo "=== GitHub (repo Settings → Secrets and variables → Actions) ==="
echo ""
echo "Render deploy runs automatically in the CI job after build (unless DEPLOY_TARGET=k8s)."
echo ""
echo "Optional — only needed to override the default:"
echo "  DEPLOY_TARGET = render    (default if unset)"
echo "  DEPLOY_TARGET = k8s       (skips Render hook; runs deploy_k8s job instead)"
echo ""
echo "--- If DEPLOY_TARGET=render (GitHub Secrets) ---"
echo "  DEPLOY_TARGET          render"
echo "  RENDER_DEPLOY_HOOK     https://api.render.com/deploy/srv-...?key=..."
echo ""
echo "--- If DEPLOY_TARGET=k8s (GitHub Secrets) ---"
echo "  DEPLOY_TARGET          k8s"
echo "  KUBE_CONFIG_PROD       base64-encoded kubeconfig"
echo "  K8S_OVERLAY_PROD       kustomize overlay path (e.g. server/cloud-infra/k8s/overlays/do-prod)"
echo "  K8S_NAMESPACE_PROD     namespace (e.g. crs-prod)"
echo ""
echo "=== Render Dashboard (only when DEPLOY_TARGET=render) ==="
echo ""
echo "Service env vars (Environment tab — NOT in GitHub):"
echo "  MONGO_URI              mongodb+srv://..."
echo "  JWT_PRIVATE_KEY        PEM one-liner (./docker/generate-jwt-keys.sh)"
echo "  JWT_PUBLIC_KEY         PEM one-liner"
echo ""
echo "Already in render.yaml (synced on blueprint apply):"
echo "  NODE_ENV, API_PREFIX, UPLOAD_DIR, CORS_ORIGINS, COOKIE_SECURE, etc."
echo ""
echo "One-time Render setup:"
echo "  1. New Blueprint → connect repo → apply render.yaml"
echo "  2. Settings → Deploy Hook → copy URL → GitHub secret RENDER_DEPLOY_HOOK"
echo "  3. autoDeploy is false — only GitHub Actions triggers deploy"
echo "  4. DNS: CNAME crs.abnjain.me → <service>.onrender.com"
echo "  5. After deploy: ./docker/smoke-test.sh https://crs.abnjain.me"
echo "  6. Admin user: Render Shell → node /app/server/dist/scripts/createUser.js ..."
echo ""

if command -v render >/dev/null 2>&1; then
  echo "Render CLI: render blueprint apply"
else
  echo "Render CLI: https://render.com/docs/cli"
fi
