version: '3.8'
services:
  frontend:
    image: abnjain/crs-frontend:latest
    restart: always
    ports:
      - "80:80"

  backend:
    image: abnjain/crs-backend:latest
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb://localhost:27017/crs
      - REDIS_URL=redis://localhost:6379
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:6
    restart: always
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7
    restart: always

volumes:
  mongo-data:
