apiVersion: v1
kind: Secret
metadata:
  name: crs-app-secrets
type: Opaque
stringData:
  JWT_PRIVATE_KEY: "REPLACE_ME_PRIVATE_KEY"
  JWT_PUBLIC_KEY: "REPLACE_ME_PUBLIC_KEY"
  MONGO_URI: "mongodb://crs-root:change-me@mongo:27017/crs?authSource=admin"
  REDIS_URL: "redis://:change-me@redis:6379"
  SMTP_HOST: ""
  SMTP_USER: ""
  SMTP_PASS: ""
  SMTP_FROM: ""
  S3_BUCKET: ""
  S3_ACCESS_KEY_ID: ""
  S3_SECRET_ACCESS_KEY: ""
  LIBRARY_FEE_WAIVER_KEY: ""
