name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repo
        uses: actions/checkout@v4

      # Step 2: Set up Docker
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build & push frontend
      - name: Build & Push Frontend Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/frontend.Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/crs-frontend:latest
            ${{ secrets.DOCKER_USERNAME }}/crs-frontend:${{ github.sha }}

      # Step 4: Build & push backend
      - name: Build & Push Backend Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/backend.Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/crs-backend:latest
            ${{ secrets.DOCKER_USERNAME }}/crs-backend:${{ github.sha }}

      # Step 5: Deploy to cloud server (via SSH + Docker Compose)
      - name: Deploy to Cloud Server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/crs-deployment
            docker-compose pull
            docker-compose up -d --force-recreate

       # Step 6: Deploy via Helm to k3s
      - name: Deploy to K3s with Helm
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            helm upgrade --install crs-app ~/infra/helm/crs-app \
              --set frontend.image=${{ secrets.DOCKER_USERNAME }}/crs-frontend:latest \
              --set backend.image=${{ secrets.DOCKER_USERNAME }}/crs-backend:latest 